# AVCORP validation: frontier models

The 25 validation games (100 rows) of AVCORP on four frontier models, with the tactic
prompt and the model's own traces from the two previous rounds, as in
`8_eval_model_trace.py`. The prompt matches Qwen's except that the system prompt drops
`/no_think`.

| alias | API id | default reasoning |
|---|---|---|
| `gpt-5.6-sol` | `gpt-5.6-sol` | effort medium |
| `claude-opus-5.5` | `claude-opus-5-5` (skipped) | adaptive, effort medium |
| `claude-opus-5.5-neutral` | `claude-opus-5-5` | adaptive, prompt-neutral wording, effort medium |
| `gemini-3.1-pro` | `gemini-3.1-pro-preview` | thinking high |
| `deepseek-v4-pro` | `deepseek-v4-pro` | thinking on, effort high |

Results go to `results/`: `raw/<alias>.jsonl` (one line per row), `raw/<alias>.errors.log`,
`eval_predictions_<alias>.csv` and `eval_summary.csv`.

In [2]:
import importlib, sys
import pandas as pd
pd.set_option("display.width", 200)

for m in ("models", "prompt", "providers", "runner"):
    if m in sys.modules:
        importlib.reload(sys.modules[m])
import models, prompt, providers, runner

## 1. Check the keys and model ids

Reads each provider's model listing; no model is called.

In [3]:
sys.argv = ["models.py", "--check"]
models.main()

openai     135 models
anthropic  13 models
deepseek   2 models
google     61 models

alias            id                        status
gpt-5.6-sol      gpt-5.6-sol               present
claude-opus-5.5  claude-opus-5-5           present
claude-opus-5.5-neutralclaude-opus-5-5           present
gemini-3.1-pro   gemini-3.1-pro-preview    present
deepseek-v4-pro  deepseek-v4-pro           present

All four models resolve.

0

## 2. Inspect a prompt

No call is made. With an alias, the prior traces are that model's stored outputs.

In [3]:
print(prompt.GAMES[:5], "...")
print({g: [int(r["round_id"]) for r in prompt.ROWS_BY_GAME[g]] for g in prompt.GAMES[:3]})

['G015', 'G028', 'G043', 'G045', 'G051'] ...
{'G015': [1, 2, 3], 'G028': [1, 2, 3, 4], 'G043': [1, 2, 3, 4, 5]}

In [4]:
system, user = runner.show_prompt("G015", 3, alias=None)

=== SYSTEM ===
You are the Investigator in a 5-player Avalon game. Your player ID is P1 and your alignment is Good. You must reason about the following four players: P2, P3, P4, P5. Reason carefully from the evidence and produce only valid JSON.

=== USER (3,787 chars) ===
Public History
[R1] Round: 1
Leader: P2
Team: P1, P2
Votes: P1:Y P2:Y P3:Y P4:Y P5:Y
Quest 1 Outcome: FAIL
[R2] Round: 2
 Leader: P3
 Team: P3, P4, P5
 Votes: P1:N P2:Y P3:Y P4:Y P5:Y
 Quest 2 Outcome: FAIL
[R3] Round: 3
 Leader: P4
 Team: P1, P4
 Votes: P1:Y P2:Y P3:Y P4:Y P5:Y
 Quest 3 Outcome: FAIL

Discussion Log
Discussion after Quest 3:

P2: "Three fails with three different setups, and the only consistent thread is P1 being on two of them and voting yes on all of them—if you’re asking me to name evil, it’s P1 and the person who most reliably greenlit bad teams: P3."

P4: "Look at the cleanest pattern: Quest 2 failed on P3/P4/P5 and every single person except P1 approved it, so the sabotage almost surely came from inside that trio—P3 was the leader and still pushed a failing team. My final call is P3 and P1."

P5: "Hard facts: Q1 failed with P1/P2, Q2 failed with P3/P4/P5, Q3 failed with P1/P4; the only pair that can cover all three fails without inventing weird stories is P2 and P4. My final two are P2 and P4."

P3: "I get why people are frustrated and want a simple culprit like P1, but that reads like scapegoating the one person who can’t defend themselves when the math already points elsewhere. If I put myself in P1’s shoes, the consistent overlap that explains every fail is P4 being on two failed quests and P2 being on the other, so my final is P2 and P4."

Given the public history and discussion log, produce a structured JSON reasoning trace with exactly the following seven keys.

abduction: a list of four objects, one per other player. Each object has the fields player, good_expl, evil_expl, and choice. The choice field must be either Good or Evil.

suspicion: a list of four objects, one per other player. Each object has the fields player, level, and reason. Valid levels are Minimal, Mild, Moderate, Strong, and Extreme.

depth: an integer, either 1 or 2. Use 2 only when at least one player has Strong or Extreme suspicion.

beliefs: a list of belief objects. Level 1 beliefs must exist for all four other players. Level 2 beliefs may exist only for players with Strong or Extreme suspicion. Each belief object has the fields level, player, and content.

statement: a string containing your public statement for this round.

deduction: a list of player IDs you believe are Evil, for example ["P3", "P4"].

tactics: a list of four objects, one per other player. Each object has the fields player and tactic. The tactic field must be exactly one of: Bayesian hedging, Bold falsehoods, Bullshitting, Cherry-picking, Confusion tactics, Defensive disclosure, Deflection, Evidence sharing, Face-saving blather, False consensus, Gaslighting, Half-truths, Hard lying, Honest mistake, Misframing, Misleading emphasis, Noisy sincerity, Obfuscatory nonsense, Omission to save face, Over-explaining, Overstated contribution, Perspective-taking, Pragmatic silence, Rational justification, Rationalized error, Reverse accusations, Self-deception, Self-justification, Sincere false belief, Strategic fabrication, Strategic omission, Strategic uncertainty, Technobabble, Truthful misdirection, Vague filler, Weaponized candor, Withholding info (WIFOM).

Self-Knowledge Elimination: you know your own alignment and actions with certainty. If a quest's outcome contradicts your known-Good behavior, eliminate suspects using the team's known composition, confidence scaling with how few possibilities remain. One remaining suspect means a definitive conclusion (Extreme suspicion, Evil abduction choice), not just strong suspicion. Example: a failed 2-player quest you were on makes the other player definitively Evil, since you always submit Pass.

Output only the JSON object. Do not include any explanation outside the JSON.

Produce the JSON reasoning trace:

## 3. Pilot: the first game of each model

Game `G015` (3 rounds) on all four models in parallel. Check the token counts below
against each provider's usage page before the full run.

In [ ]:
runner.run_all(games=1)

In [ ]:
runner.progress()

## 4. The full run

All four models in parallel. Finished rows are skipped, so it is safe to interrupt and
re-run. Each model runs `runner.GAME_WORKERS` games at once (default 5); the rounds
of a game always run in order.

In [5]:
runner.run_all()

=== 4 models, 25 games each ===
  gpt-5.6-sol      start: 25 games, 5 at a time
  claude-opus-5.5  start: 25 games, 5 at a time
  gemini-3.1-pro   start: 25 games, 5 at a time
  deepseek-v4-pro  start: 25 games, 5 at a time
  gpt-5.6-sol      G015 R1    1/100    13.9s  in 701 out 974 (reasoning 92)
  gpt-5.6-sol      G043 R1    2/100    15.2s  in 840 out 1043 (reasoning 179)
  gpt-5.6-sol      G028 R1    3/100    15.2s  in 811 out 1112 (reasoning 159)
  claude-opus-5.5  G045 R1    1/100    16.1s  in 1379 out 1218
  claude-opus-5.5  G043 R1    2/100    16.4s  in 1331 out 1137
  gpt-5.6-sol      G051 R1    4/100    17.0s  in 868 out 1293 (reasoning 393)
  gpt-5.6-sol      G045 R1    5/100    17.4s  in 870 out 1317 (reasoning 392)
  claude-opus-5.5  G015 R1    3/100    17.8s  in 1120 out 1223
  claude-opus-5.5  G051 R1    4/100    17.9s  in 1357 out 1440
  gemini-3.1-pro   G015 R1    1/100    19.9s  in 717 out 2681
  gemini-3.1-pro   G045 R1    2/100    20.7s  in 890 out 2616
  gemini-3.1-pro   G051 R1    3/100    25.8s  in 889 out 3234
  gemini-3.1-pro   G028 R1    4/100    26.4s  in 832 out 3631
  claude-opus-5.5  G028 R1    5/100    28.3s  in 1268 out 1895
  gpt-5.6-sol      G045 R2    6/100    15.3s  in 1940 out 1379 (reasoning 310)
  gpt-5.6-sol      G051 R2    7/100    19.1s  in 1877 out 1635 (reasoning 516)
  gpt-5.6-sol      G043 R2    8/100    21.2s  in 1866 out 1855 (reasoning 684)
  gemini-3.1-pro   G043 R1    5/100    36.7s  in 863 out 4889
  claude-opus-5.5  G045 R2    6/100    21.5s  in 2786 out 1938
  gpt-5.6-sol      G015 R2    9/100    24.1s  in 1874 out 2020 (reasoning 880)
  gpt-5.6-sol      G028 R2   10/100    22.8s  in 1960 out 2062 (reasoning 862)
  claude-opus-5.5  G051 R2    7/100    20.2s  in 2669 out 1828
  claude-opus-5.5  G043 R2    8/100    22.1s  in 2715 out 2057
  claude-opus-5.5  G043 R3  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  claude-opus-5.5  G015 R2    9/100    22.3s  in 2794 out 2098
  claude-opus-5.5  G051 R3  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  claude-opus-5.5  G015 R3  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  gpt-5.6-sol      G045 R3   11/100    15.9s  in 3097 out 1503 (reasoning 262)
  gpt-5.6-sol      G015 R3   12/100    12.0s  in 3043 out 1296 (reasoning 208)
  gpt-5.6-sol      G028 R3   13/100    16.0s  in 3232 out 1617 (reasoning 379)
  gpt-5.6-sol      G043 R3   14/100    18.0s  in 3141 out 1650 (reasoning 340)
  claude-opus-5.5  G028 R2   10/100    28.1s  in 2921 out 2349
  claude-opus-5.5  G028 R3  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  claude-opus-5.5  G045 R3   11/100    22.0s  in 4412 out 1859
  claude-opus-5.5  G045 R4  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  claude-opus-5.5  G088 R1   12/100    15.2s  in 1312 out 1394
  gpt-5.6-sol      G051 R3   15/100    25.7s  in 3167 out 2295 (reasoning 1116)
  claude-opus-5.5  G077 R1   13/100    22.1s  in 1319 out 1573
  gemini-3.1-pro   G051 R2    6/100    38.1s  in 2117 out 5070
  gemini-3.1-pro   G015 R2    7/100    43.9s  in 2057 out 5856
  gpt-5.6-sol      G077 R1   16/100    14.4s  in 830 out 1313 (reasoning 361)
  gpt-5.6-sol      G045 R4   17/100    16.6s  in 3407 out 1670 (reasoning 379)
  gemini-3.1-pro   G028 R2    8/100    43.1s  in 2161 out 5853
  claude-opus-5.5  G089 R1   14/100    22.7s  in 1343 out 1856
  claude-opus-5.5  G092 R1   15/100    13.6s  in 1356 out 1134
  deepseek-v4-pro  G043 R1    1/100    72.6s  in 930 out 6466 (reasoning 5602)
  gemini-3.1-pro   G043 R2    9/100    37.3s  in 2050 out 5535
  gpt-5.6-sol      G088 R1   18/100    13.3s  in 839 out 1149 (reasoning 218)
  gpt-5.6-sol      G028 R4   19/100    21.3s  in 3550 out 1865 (reasoning 628)
  gpt-5.6-sol      G043 R4   20/100    22.3s  in 3476 out 1954 (reasoning 516)
  deepseek-v4-pro  G015 R1    2/100    80.0s  in 788 out 7499 (reasoning 6571)
  gpt-5.6-sol      G045 R5   21/100    15.2s  in 3664 out 1568 (reasoning 288)
  gemini-3.1-pro   G045 R2   10/100    59.9s  in 2058 out 7477
  gpt-5.6-sol      G077 R2   22/100    16.9s  in 1927 out 1499 (reasoning 489)
  claude-opus-5.5  G088 R2   16/100    21.6s  in 2962 out 2116
  gemini-3.1-pro   G015 R3   11/100    20.1s  in 3276 out 2951
  claude-opus-5.5  G096 R1   17/100    26.0s  in 1192 out 2386
  claude-opus-5.5  G077 R2   18/100    28.0s  in 2735 out 2565
  claude-opus-5.5  G092 R2   19/100    18.2s  in 2691 out 1727
  claude-opus-5.5  G077 R3  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  gpt-5.6-sol      G088 R2   23/100    17.7s  in 1937 out 1587 (reasoning 462)
  claude-opus-5.5  G089 R2   20/100    22.6s  in 2846 out 2201
  gemini-3.1-pro   G051 R3   12/100    31.1s  in 3510 out 4270
  gpt-5.6-sol      G089 R1   24/100    20.6s  in 852 out 1690 (reasoning 733)
  gpt-5.6-sol      G092 R1   25/100    17.8s  in 872 out 1533 (reasoning 631)
  deepseek-v4-pro  G045 R1    3/100   100.9s  in 959 out 9136 (reasoning 8296)
  gpt-5.6-sol      G077 R3   26/100    20.1s  in 3051 out 1910 (reasoning 652)
  claude-opus-5.5  G088 R3   21/100    21.2s  in 4610 out 2064
  deepseek-v4-pro  G028 R1    4/100   104.5s  in 901 out 9813 (reasoning 8837)
  claude-opus-5.5  G088 R4  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  gemini-3.1-pro   G043 R3   13/100    32.4s  in 3421 out 4717
  gemini-3.1-pro   G077 R1   14/100    25.8s  in 858 out 3579
  deepseek-v4-pro  G051 R1    5/100   109.8s  in 962 out 10482 (reasoning 9610)
  gpt-5.6-sol      G088 R3   27/100    17.6s  in 3144 out 1635 (reasoning 394)
  gpt-5.6-sol      G089 R2   28/100    15.3s  in 1962 out 1413 (reasoning 409)
  claude-opus-5.5  G096 R2   22/100    25.5s  in 3196 out 2447
  claude-opus-5.5  G092 R3   23/100    23.3s  in 4066 out 2284
  gpt-5.6-sol      G043 R5   29/100    36.7s  in 3942 out 3041 (reasoning 1701)
  gemini-3.1-pro   G088 R1   15/100    18.4s  in 863 out 2514
  claude-opus-5.5  G112 R1   24/100    22.9s  in 1357 out 1877
  gpt-5.6-sol      G092 R2   30/100    15.7s  in 1882 out 1394 (reasoning 409)
  gemini-3.1-pro   G045 R3   16/100    36.4s  in 3345 out 4903
  claude-opus-5.5  G112 R2  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  claude-opus-5.5  G089 R3   25/100    27.3s  in 4589 out 2569
  claude-opus-5.5  G133 R1   26/100    18.2s  in 1270 out 1704
  gemini-3.1-pro   G028 R3   17/100    55.5s  in 3407 out 7388
  gpt-5.6-sol      G096 R1   31/100    13.0s  in 760 out 1195 (reasoning 237)
  gpt-5.6-sol      G088 R4   32/100    18.0s  in 3469 out 1675 (reasoning 403)
  gpt-5.6-sol      G089 R3   33/100    18.5s  in 3089 out 1732 (reasoning 516)
  gpt-5.6-sol      G092 R3   34/100    17.5s  in 2945 out 1410 (reasoning 219)
  gpt-5.6-sol      G077 R4   35/100    31.3s  in 3380 out 2579 (reasoning 1304)
  claude-opus-5.5  G149 R1   27/100    13.8s  in 1356 out 1344
  claude-opus-5.5  G092 R4   28/100    23.2s  in 4621 out 2262
  claude-opus-5.5  G096 R3   29/100    25.9s  in 5092 out 2690
  claude-opus-5.5  G089 R4   30/100    23.3s  in 4923 out 2356
  gpt-5.6-sol      G096 R2   36/100    18.5s  in 2016 out 1590 (reasoning 516)
  claude-opus-5.5  G089 R5  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  gemini-3.1-pro   G043 R4   18/100    39.4s  in 3558 out 6028
  claude-opus-5.5  G133 R2   31/100    23.4s  in 2668 out 2128
  gpt-5.6-sol      G089 R4   37/100    16.8s  in 3356 out 1649 (reasoning 277)
  gemini-3.1-pro   G077 R2   19/100    38.5s  in 2095 out 5728
  gemini-3.1-pro   G088 R2   20/100    35.3s  in 2121 out 4400
  gpt-5.6-sol      G112 R1   38/100    17.7s  in 844 out 1507 (reasoning 478)
  gpt-5.6-sol      G092 R4   39/100    20.7s  in 3307 out 1824 (reasoning 432)
  gpt-5.6-sol      G088 R5   40/100    25.6s  in 3646 out 2344 (reasoning 981)
  gemini-3.1-pro   G028 R4   21/100    31.9s  in 3610 out 3988
  claude-opus-5.5  G149 R2   32/100    24.5s  in 2629 out 2244
  gpt-5.6-sol      G096 R3   41/100    15.8s  in 3145 out 1478 (reasoning 297)
  claude-opus-5.5  G092 R5   33/100    27.1s  in 5041 out 2708
  claude-opus-5.5  G151 R1   34/100    19.6s  in 1298 out 1779
  gpt-5.6-sol      G112 R2   42/100    16.1s  in 1988 out 1464 (reasoning 387)
  deepseek-v4-pro  G015 R2    6/100    87.0s  in 2016 out 8387 (reasoning 7378)
  gpt-5.6-sol      G133 R1   43/100    13.6s  in 802 out 1291 (reasoning 321)
  claude-opus-5.5  G096 R4   35/100    29.8s  in 5348 out 2982
  gemini-3.1-pro   G045 R4   22/100    55.6s  in 3626 out 7070
  claude-opus-5.5  G162 R1   36/100    14.1s  in 1331 out 1211
  claude-opus-5.5  G133 R3   37/100    31.1s  in 4294 out 2834
  claude-opus-5.5  G133 R4  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  claude-opus-5.5  G162 R2  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  gpt-5.6-sol      G089 R5   44/100    35.0s  in 3757 out 2824 (reasoning 1275)
  gpt-5.6-sol      G096 R4   45/100    23.0s  in 3362 out 2048 (reasoning 688)
  claude-opus-5.5  G149 R3   38/100    25.7s  in 4153 out 2589
  claude-opus-5.5  G149 R4  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  gpt-5.6-sol      G092 R5   46/100    33.2s  in 3682 out 2761 (reasoning 1287)
  gemini-3.1-pro   G088 R3   23/100    36.8s  in 3385 out 4518
  gpt-5.6-sol      G133 R2   47/100    18.1s  in 1943 out 1603 (reasoning 412)
  claude-opus-5.5  G151 R2   39/100    20.6s  in 2912 out 2012
  gemini-3.1-pro   G089 R1   24/100    29.2s  in 880 out 3610
  gpt-5.6-sol      G112 R3   48/100    24.0s  in 3161 out 1918 (reasoning 656)
  gpt-5.6-sol      G149 R1   49/100    11.0s  in 857 out 1041 (reasoning 204)
  claude-opus-5.5  G096 R5   40/100    26.5s  in 5372 out 2844
  claude-opus-5.5  G165 R1   41/100    18.4s  in 1357 out 1635
  gemini-3.1-pro   G043 R5   25/100    52.3s  in 3807 out 7686
  claude-opus-5.5  G173 R1   42/100    19.7s  in 1315 out 1779
  deepseek-v4-pro  G015 R3    7/100    34.3s  in 3064 out 4197 (reasoning 3147)
  gpt-5.6-sol      G162 R1   50/100    12.3s  in 841 out 1025 (reasoning 125)
  deepseek-v4-pro  G043 R2    8/100   134.4s  in 1965 out 12289 (reasoning 11259)
  gpt-5.6-sol      G151 R1   51/100    22.0s  in 838 out 1835 (reasoning 849)
  gpt-5.6-sol      G133 R3   52/100    23.3s  in 3262 out 2130 (reasoning 879)
  claude-opus-5.5  G191 R1   43/100    14.5s  in 1311 out 1221
  claude-opus-5.5  G175 R1   44/100    24.2s  in 1348 out 2075
  gpt-5.6-sol      G096 R5   53/100    28.0s  in 3670 out 2418 (reasoning 970)
  claude-opus-5.5  G175 R2  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  claude-opus-5.5  G151 R3   45/100    26.5s  in 4502 out 2684
  gemini-3.1-pro   G045 R5   26/100    40.9s  in 3852 out 5248
  claude-opus-5.5  G165 R2   46/100    18.0s  in 2828 out 1772
  claude-opus-5.5  G165 R3  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  gemini-3.1-pro   G077 R3   27/100    68.1s  in 3577 out 8982
  gemini-3.1-pro   G089 R2   28/100    31.4s  in 2096 out 3942
  claude-opus-5.5  G173 R2   47/100    21.8s  in 2835 out 2097
  gpt-5.6-sol      G149 R2   54/100    30.5s  in 1829 out 2624 (reasoning 1540)
  deepseek-v4-pro  G028 R2    9/100   118.9s  in 2085 out 11604 (reasoning 10406)
  gpt-5.6-sol      G151 R2   55/100    16.7s  in 2002 out 1474 (reasoning 290)
  gpt-5.6-sol      G165 R1   56/100    13.2s  in 862 out 1196 (reasoning 239)
  gpt-5.6-sol      G133 R4   57/100    18.1s  in 3586 out 1756 (reasoning 423)
  gemini-3.1-pro   G092 R1   29/100    29.4s  in 893 out 3652
  claude-opus-5.5  G191 R2   48/100    20.0s  in 2640 out 1742
  claude-opus-5.5  G191 R3  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  gpt-5.6-sol      G162 R2   58/100    30.0s  in 1856 out 2364 (reasoning 1288)
  claude-opus-5.5  G203 R1   49/100    21.4s  in 1368 out 2038
  claude-opus-5.5  G207 R1   50/100    21.5s  in 1311 out 2076
  claude-opus-5.5  G212 R1   51/100    18.5s  in 1343 out 1537
  gemini-3.1-pro   G088 R4   30/100    51.4s  in 3570 out 6815
  gpt-5.6-sol      G165 R2   59/100    14.5s  in 1952 out 1336 (reasoning 305)
  claude-opus-5.5  G173 R3   52/100    19.7s  in 4544 out 2111
  gpt-5.6-sol      G133 R5   60/100    14.5s  in 3660 out 1526 (reasoning 209)
  claude-opus-5.5  G173 R4  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  gpt-5.6-sol      G149 R3   61/100    24.6s  in 3004 out 2022 (reasoning 802)
  claude-opus-5.5  G213 R1   53/100    19.3s  in 1179 out 1543
  gpt-5.6-sol      G151 R3   62/100    25.6s  in 3271 out 2319 (reasoning 967)
  deepseek-v4-pro  G045 R2   10/100   149.0s  in 1952 out 13854 (reasoning 12753)
  gpt-5.6-sol      G162 R3   63/100    17.7s  in 3070 out 1568 (reasoning 301)
  gemini-3.1-pro   G096 R1   31/100    37.9s  in 770 out 5226
  claude-opus-5.5  G212 R2   54/100    17.6s  in 2701 out 1683
  gpt-5.6-sol      G173 R1   64/100    11.3s  in 839 out 1048 (reasoning 158)
  claude-opus-5.5  G212 R3  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  claude-opus-5.5  G203 R2   55/100    21.9s  in 2863 out 2033
  claude-opus-5.5  G213 R2  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  claude-opus-5.5  G207 R2   56/100    22.1s  in 2968 out 2418
  gemini-3.1-pro   G092 R2   32/100    30.3s  in 2055 out 3725
  gpt-5.6-sol      G165 R3   65/100    23.0s  in 3109 out 1982 (reasoning 732)
  gpt-5.6-sol      G191 R1   66/100    13.1s  in 834 out 1195 (reasoning 242)
  gpt-5.6-sol      G149 R4   67/100    18.8s  in 3285 out 1759 (reasoning 516)
  gpt-5.6-sol      G149 R5  FAILED RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organizati
  gpt-5.6-sol      G207 R1  FAILED RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organizati
  gemini-3.1-pro   G089 R3   33/100    50.4s  in 3406 out 6364
  gpt-5.6-sol      G212 R1  FAILED RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organizati
  claude-opus-5.5  G228 R1   57/100    24.0s  in 1325 out 2245
  gpt-5.6-sol      G175 R1   68/100    18.4s  in 863 out 1657 (reasoning 599)
  gpt-5.6-sol      G213 R1  FAILED RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organizati
  gpt-5.6-sol      G175 R2  FAILED RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organizati
  gpt-5.6-sol      G228 R1  FAILED RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organizati
  gpt-5.6-sol      G236 R1  FAILED RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organizati
  claude-opus-5.5  G236 R1   58/100    19.3s  in 1295 out 1565
  gpt-5.6-sol      G173 R2   69/100    20.1s  in 1861 out 1725 (reasoning 516)
  gemini-3.1-pro   G088 R5   34/100    36.4s  in 3786 out 4445
  gpt-5.6-sol      G173 R3  FAILED RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organizati
  claude-opus-5.5  G203 R3   59/100    18.7s  in 4409 out 1911
  claude-opus-5.5  G207 R3   60/100    19.9s  in 4821 out 2111
  gemini-3.1-pro   G077 R4   35/100    61.1s  in 3899 out 7665
  gpt-5.6-sol      G191 R2   70/100    15.3s  in 1845 out 1362 (reasoning 231)
  gpt-5.6-sol      G191 R3  FAILED RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organizati
  gpt-5.6-sol      G203 R1   71/100    19.9s  in 871 out 1800 (reasoning 659)
  gpt-5.6-sol      G203 R2  FAILED RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organizati
  gpt-5.6-sol      DONE ok=71 skipped=0 failed=10
  deepseek-v4-pro  G051 R2   11/100   179.9s  in 1944 out 16385 (reasoning 15278)
  claude-opus-5.5  G228 R2   61/100    23.5s  in 3019 out 2157
  gemini-3.1-pro   G112 R1   36/100    22.8s  in 869 out 2687
  claude-opus-5.5  G236 R2   62/100    24.9s  in 2811 out 2068
  deepseek-v4-pro  G077 R1   12/100    97.1s  in 921 out 8731 (reasoning 7756)
  gemini-3.1-pro   G092 R3   37/100    47.7s  in 3173 out 5953
  gemini-3.1-pro   G133 R1   38/100    29.8s  in 827 out 3791
  claude-opus-5.5  G228 R3   63/100    20.3s  in 4658 out 2071
  claude-opus-5.5  G236 R3   64/100    27.9s  in 4475 out 2730
  claude-opus-5.5  G236 R4  FAILED Empty: claude-opus-5.5: empty response (finish=content_filter)
  deepseek-v4-pro  G045 R3   13/100    77.0s  in 3160 out 8171 (reasoning 7086)
  gemini-3.1-pro   G089 R4   39/100    62.9s  in 3676 out 8353
  claude-opus-5.5  G228 R4   65/100    24.9s  in 4768 out 2563
  claude-opus-5.5  DONE ok=65 skipped=0 failed=19
  gemini-3.1-pro   G112 R2   40/100    49.7s  in 1960 out 6428
  gemini-3.1-pro   G133 R2   41/100    49.1s  in 2055 out 6018
  gemini-3.1-pro   G096 R2   42/100   110.6s  in 2281 out 14399
  deepseek-v4-pro  G028 R3   14/100   145.5s  in 3369 out 13419 (reasoning 12303)
  gemini-3.1-pro   G092 R4   43/100    75.8s  in 3394 out 9864
  deepseek-v4-pro  G051 R3   15/100    94.3s  in 3231 out 9495 (reasoning 8259)
  gemini-3.1-pro   G112 R3   44/100    41.3s  in 3352 out 6056
  gemini-3.1-pro   G133 R3   45/100    51.9s  in 3418 out 6962
  gemini-3.1-pro   G149 R1   46/100    27.0s  in 875 out 3865
  gemini-3.1-pro   G096 R3   47/100    61.4s  in 3828 out 8344
  gemini-3.1-pro   G092 R5   48/100    45.3s  in 3716 out 6541
  deepseek-v4-pro  G088 R1   16/100    47.6s  in 928 out 4635 (reasoning 3782)
  gemini-3.1-pro   G133 R4   49/100    35.7s  in 3816 out 5230
  gemini-3.1-pro   G089 R5   50/100   117.7s  in 3803 out 16213
  gemini-3.1-pro   G151 R1   51/100    28.2s  in 852 out 3370
  gemini-3.1-pro   G149 R2   52/100    46.5s  in 2139 out 6762
  deepseek-v4-pro  G043 R3   17/100   258.7s  in 3113 out 23533 (reasoning 22445)
  deepseek-v4-pro  G045 R4   18/100   145.6s  in 3397 out 13722 (reasoning 12551)
  gemini-3.1-pro   G162 R1   53/100    24.8s  in 867 out 3272
  gemini-3.1-pro   G096 R4   54/100    49.8s  in 4209 out 6885
  deepseek-v4-pro  G077 R2   19/100   176.6s  in 2049 out 16331 (reasoning 15311)
  gemini-3.1-pro   G133 R5   55/100    39.4s  in 3826 out 5552
  gemini-3.1-pro   G165 R1   56/100    16.7s  in 883 out 2098
  gemini-3.1-pro   G151 R2   57/100    45.2s  in 2333 out 6169
  gemini-3.1-pro   G149 R3   58/100    45.9s  in 3455 out 6549
  gemini-3.1-pro   G096 R5   59/100    36.1s  in 4149 out 5194
  gemini-3.1-pro   G162 R2   60/100    62.9s  in 2031 out 8035
  deepseek-v4-pro  G028 R4   20/100   168.1s  in 3531 out 16223 (reasoning 15014)
  gemini-3.1-pro   G173 R1   61/100    29.3s  in 857 out 4000
  gemini-3.1-pro   G149 R4   62/100    48.0s  in 3603 out 6499
  gemini-3.1-pro   G151 R3   63/100    57.7s  in 3820 out 7762
  deepseek-v4-pro  G088 R2   21/100   127.6s  in 1954 out 12219 (reasoning 11143)
  deepseek-v4-pro  G045 R5   22/100    89.1s  in 3491 out 8535 (reasoning 7312)
  gemini-3.1-pro   G165 R2   64/100    64.1s  in 2056 out 8796
  gemini-3.1-pro   G173 R2   65/100    32.5s  in 2086 out 4242
  gemini-3.1-pro   G175 R1   66/100    26.5s  in 878 out 3183
  gemini-3.1-pro   G149 R5   67/100    50.3s  in 3909 out 6760

                 rows  games_complete  mean_in  mean_gen  mean_reasoning  total_in  total_gen  hit_max  error_lines
model
gpt-5.6-sol        71              15     2272      1695           546.0    161341     120326        0           10
claude-opus-5.5    65               6     2779      2012             NaN    180628     130787        0           19
gemini-3.1-pro     99              24     2539      5840             NaN    251342     578122        0            1
deepseek-v4-pro   100              25     2398     13353         12271.0    239790    1335312        1            0

### Or one model at a time

`games=` takes an int (the first n games) or a list of game ids. Set `game_workers` as `runner.run_model("gpt-5.6-sol", game_workers=10)`

In [7]:
runner.run_model("gpt-5.6-sol")

  gpt-5.6-sol      start: 25 games, 5 at a time
  gpt-5.6-sol      G191 R3   72/100    17.0s  in 3109 out 1555 (reasoning 269)
  gpt-5.6-sol      G175 R2   73/100    20.9s  in 2043 out 1847 (reasoning 638)
  gpt-5.6-sol      G149 R5   74/100    23.1s  in 3550 out 1975 (reasoning 661)
  gpt-5.6-sol      G173 R3   75/100    26.9s  in 3205 out 2228 (reasoning 886)
  gpt-5.6-sol      G203 R2   76/100    28.3s  in 2128 out 2284 (reasoning 1014)
  gpt-5.6-sol      G191 R4   77/100    16.6s  in 3513 out 1530 (reasoning 256)
  gpt-5.6-sol      G175 R3   78/100    18.8s  in 3346 out 1861 (reasoning 516)
  gpt-5.6-sol      G207 R1   79/100    16.9s  in 831 out 1447 (reasoning 409)
  gpt-5.6-sol      G191 R5   80/100    16.3s  in 3711 out 1612 (reasoning 281)
  gpt-5.6-sol      G203 R3   81/100    26.5s  in 3469 out 2305 (reasoning 1034)
  gpt-5.6-sol      G207 R2   82/100    18.2s  in 1932 out 1626 (reasoning 380)
  gpt-5.6-sol      G173 R4   83/100    37.6s  in 3689 out 3222 (reasoning 1740)
  gpt-5.6-sol      G212 R1   84/100    17.4s  in 855 out 1500 (reasoning 622)
  gpt-5.6-sol      G175 R4   85/100    28.3s  in 3636 out 2640 (reasoning 1247)
  gpt-5.6-sol      G207 R3   86/100    15.3s  in 3255 out 1490 (reasoning 274)
  gpt-5.6-sol      G213 R1   87/100    18.9s  in 744 out 1590 (reasoning 688)
  gpt-5.6-sol      G228 R1   88/100    14.2s  in 853 out 1289 (reasoning 298)
  gpt-5.6-sol      G236 R1   89/100    12.6s  in 811 out 1153 (reasoning 207)
  gpt-5.6-sol      G212 R2   90/100    16.8s  in 1854 out 1426 (reasoning 418)
  gpt-5.6-sol      G213 R2   91/100    17.8s  in 1869 out 1560 (reasoning 516)
  gpt-5.6-sol      G236 R2   92/100    22.7s  in 1976 out 1850 (reasoning 696)
  gpt-5.6-sol      G228 R2   93/100    25.9s  in 2017 out 2221 (reasoning 1107)
  gpt-5.6-sol      G212 R3   94/100    24.1s  in 2935 out 2011 (reasoning 817)
  gpt-5.6-sol      G213 R3   95/100    20.2s  in 3049 out 1704 (reasoning 460)
  gpt-5.6-sol      G228 R3   96/100    24.7s  in 3185 out 2075 (reasoning 926)
  gpt-5.6-sol      G236 R3   97/100    28.6s  in 3218 out 2392 (reasoning 960)
  gpt-5.6-sol      G228 R4   98/100    19.6s  in 3406 out 1729 (reasoning 516)
  gpt-5.6-sol      G236 R4   99/100    34.6s  in 3717 out 2846 (reasoning 1452)
  gpt-5.6-sol      G236 R5  100/100    25.4s  in 3899 out 2230 (reasoning 849)
  gpt-5.6-sol      DONE ok=29 skipped=71 failed=0

{'ok': 29, 'skipped': 71, 'failed': 0}

In [6]:
runner.run_model("claude-opus-5.5")

  claude-opus-5.5  start: 25 games, 5 at a time
  claude-opus-5.5  G045 R4  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G015 R3  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G051 R3  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G043 R3  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G028 R3  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G088 R4  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G089 R5  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G133 R4  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G077 R3  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G149 R4  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G175 R3  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G162 R2  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G191 R4  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G212 R3  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G213 R3  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  G236 R4  FAILED Refused: claude-opus-5.5: refusal (category=reasoning_extraction, explanation=This request was blocked as it seems to violate Anthropic's Terms of Service restrictions o
  claude-opus-5.5  DONE ok=0 skipped=72 failed=16

{'ok': 0, 'skipped': 72, 'failed': 16}

In [3]:
runner.run_model("claude-opus-5.5-neutral", games=["G015", "G043", "G162"])

  claude-opus-5.5-neutral start: 3 games, 5 at a time
  claude-opus-5.5-neutral G162 R1    1/100    11.6s  in 1320 out 1080
  claude-opus-5.5-neutral G043 R1    2/100    17.1s  in 1320 out 1714 (reasoning 229)
  claude-opus-5.5-neutral G015 R1    3/100    18.1s  in 1109 out 1871 (reasoning 343)
  claude-opus-5.5-neutral G162 R2    4/100    25.1s  in 2573 out 2335 (reasoning 960)
  claude-opus-5.5-neutral G015 R2    5/100    24.1s  in 3078 out 2536 (reasoning 742)
  claude-opus-5.5-neutral G043 R2    6/100    26.8s  in 3042 out 2735 (reasoning 945)
  claude-opus-5.5-neutral G015 R3    7/100    17.3s  in 4912 out 1977 (reasoning 293)
  claude-opus-5.5-neutral G162 R3    8/100    31.0s  in 4177 out 3145 (reasoning 1217)
  claude-opus-5.5-neutral G043 R3    9/100    25.4s  in 4997 out 2662 (reasoning 740)
  claude-opus-5.5-neutral G043 R4   10/100    33.9s  in 5261 out 3254 (reasoning 1215)
  claude-opus-5.5-neutral G043 R5   11/100    32.6s  in 5828 out 3464 (reasoning 1362)
  claude-opus-5.5-neutral DONE ok=11 skipped=0 failed=0

{'ok': 11, 'skipped': 0, 'failed': 0}

In [4]:
runner.run_model("claude-opus-5.5-neutral")  # neutral wording; the run above is refused as reasoning extraction

  claude-opus-5.5-neutral start: 25 games, 5 at a time
  claude-opus-5.5-neutral G236 R2   94/100    23.5s  in 3149 out 2308 (reasoning 539)
  claude-opus-5.5-neutral G228 R2   95/100    27.5s  in 3103 out 2467 (reasoning 693)
  claude-opus-5.5-neutral G236 R3   96/100    28.3s  in 5020 out 2853 (reasoning 861)
  claude-opus-5.5-neutral G228 R3   97/100    37.1s  in 4981 out 3394 (reasoning 1422)
  claude-opus-5.5-neutral G236 R4   98/100    31.8s  in 5516 out 3302 (reasoning 1204)
  claude-opus-5.5-neutral G228 R4   99/100    23.9s  in 5536 out 2523 (reasoning 729)
  claude-opus-5.5-neutral G236 R5  100/100    40.0s  in 5756 out 3748 (reasoning 1432)
  claude-opus-5.5-neutral DONE ok=7 skipped=93 failed=0

{'ok': 7, 'skipped': 93, 'failed': 0}

In [8]:
runner.run_model("gemini-3.1-pro")

  gemini-3.1-pro   start: 25 games, 5 at a time
  gemini-3.1-pro   G236 R5  100/100    62.3s  in 3837 out 8034
  gemini-3.1-pro   DONE ok=1 skipped=99 failed=0

{'ok': 1, 'skipped': 99, 'failed': 0}

In [ ]:
runner.run_model("deepseek-v4-pro")

### A subset in parallel

```python
runner.run_all(["claude-opus-5.5", "gemini-3.1-pro"])
```

## 5. Progress and what is left

In [5]:
runner.progress()

                         rows  games_complete  mean_in  mean_gen  mean_reasoning  rows_with_reasoning  total_in  total_gen  hit_max  error_lines
model
gpt-5.6-sol               100              25     2371      1755             589                  100    237146     175524        0           10
claude-opus-5.5            72               9     2876      2036             513                    1    207046     146586        0          152
claude-opus-5.5-neutral   100              25     3630      2354             629                  100    362973     235446        0           12
gemini-3.1-pro            100              25     2552      5862            4608                  100    255179     586156        0            1
deepseek-v4-pro           100              25     2398     13353           12271                  100    239790    1335312        1            0

In [ ]:
{a: len(v) for a, v in runner.pending().items()}

## 6. Score

`allow_partial=True` scores a model's complete games only.

In [6]:
summary = runner.score_all()
summary[["run", "n", "games", "game_exact_count", "game_exact_match", "game_f1", "f1", "macro_f1",
         "parse_failures", "hit_max_new_tokens"]]

                       run    n  games  game_exact_count  game_exact_match  game_f1        f1  macro_f1  parse_failures  hit_max_new_tokens
0              gpt-5.6-sol  100     25                16              0.64     0.74  0.716113  0.711667               0                   0
1  claude-opus-5.5-neutral  100     25                18              0.72     0.80  0.796992  0.796667               0                   0
2           gemini-3.1-pro  100     25                14              0.56     0.68  0.672043  0.658333               0                   0
3          deepseek-v4-pro  100     25                12              0.48     0.62  0.624365  0.620000               1                   1

### Next to the Qwen tactic runs

In [7]:
from pathlib import Path
QWEN = Path("../../trained/eval-test-model-trace/self-chain")
rows = []
for folder, label in [("tactic-grpo-h100-g16", "qwen run 6"), ("tactic-reward-grpo-h100-g16", "qwen run 7")]:
    p = QWEN / folder / "eval_summary.csv"
    if p.exists():
        for _, r in pd.read_csv(p).iterrows():
            rows.append({"run": "qwen tactic base" if r["stage"] == "base" else f"{label} {r['stage']}",
                         **{k: r[k] for k in ["n", "games", "game_exact_count", "game_exact_match", "game_f1", "f1", "macro_f1"]}})
cols = ["run", "n", "games", "game_exact_count", "game_exact_match", "game_f1", "f1", "macro_f1"]
both = pd.concat([summary[cols], pd.DataFrame(rows).drop_duplicates("run")[cols]], ignore_index=True)
both

                       run    n  games  game_exact_count  game_exact_match   game_f1        f1  macro_f1
0              gpt-5.6-sol  100     25                16              0.64  0.740000  0.716113  0.711667
1  claude-opus-5.5-neutral  100     25                18              0.72  0.800000  0.796992  0.796667
2           gemini-3.1-pro  100     25                14              0.56  0.680000  0.672043  0.658333
3          deepseek-v4-pro  100     25                12              0.48  0.620000  0.624365  0.620000
4         qwen tactic base  100     25                12              0.48  0.717391  0.471380  0.372333
5           qwen run 6 sft  100     25                13              0.52  0.747475  0.599440  0.568000
6          qwen run 6 grpo  100     25                12              0.48  0.846847  0.787472  0.789667
7           qwen run 7 sft  100     25                12              0.48  0.734694  0.578035  0.541667
8          qwen run 7 grpo  100     25                18              0.72  0.882353  0.781327  0.781667